on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
        - goarch: "386"
          goos: darwin
    steps:
    - uses: actions/checkout@v3
    - name: Set APP_VERSION from release tag
      run: echo APP_VERSION=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: -X "cmd.appVersion=${{ env.APP_VERSION }}"
